export const metadata = {
  title: "Product",
  description: "Generated by HSR",
};

function getRandomInt(count: number) {
  return Math.floor(Math.random() * count);
}

export default function ProductLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const random = getRandomInt(2);

  if (random === 1) {
    throw new Error("Error loading product...");
  }

  return (
    <>
      <div
        style={{
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          flexDirection: "column",
          marginTop: "1.5rem",
          width: "100%",
        }}
      >
        <div
          style={{
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            flexDirection: "column",
            padding: "1rem",
            width: "50%",
            border: "1px solid gray",
            background: "#1c212f",
          }}
        >
          <h3>Our Products</h3>
        </div>
      </div>

      {children}
    </>
  );
}
