numbers = [56, 32, 98, 2, 98, 5, 1, 21, 32, 14, 5, 7, 9, 10]
print("Original list is", numbers)
numbers.reverse()
print("Reverse list is", numbers)
print("Length of list is: ", len(numbers))
print("Maximum number of list is: ", max(numbers))
print("Minimum number of list is: ", min(numbers))
numbers.append(100)     #Insert element in last of the list
numbers.append(76)
print("After append: ", numbers)
numbers.insert(2, 55)
numbers.insert(3, 5)
numbers.insert(0, 66)
print("After insert:", numbers)
numbers.sort()
print("Sorted list is: ", numbers)
numbers.remove(5)
numbers.remove(10)
numbers.remove(100)
print("After remove: ", numbers)
numbers.pop()       #Remove last element of the list
numbers.pop()
numbers.pop()
print("After pop: ", numbers)
